# docker-compose.prod.yml
version: '3.8'

services:
  frontend:
    build:
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Remove development-specific volumes
    volumes:
      - ${LOCAL_SCHEMA_DIR:-null}:/usr/src/app/schema:ro

  backend:
    environment:
      - DEV_MODE=0
      - NODE_ENV=production
    restart: unless-stopped
    # Use named volume for production data
    volumes:
      - participant_data:/data

  nginx:
    restart: unless-stopped
    # Add production-specific configurations
    volumes:
      - ./config/nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/ssl:/etc/nginx/ssl:ro
      - ${LOCAL_SCHEMA_DIR:-null}:/usr/share/nginx/html/schema:ro
    # Add SSL configuration
    ports:
      - "80:80"
      - "443:443"

volumes:
  participant_data:
    driver: local  # Can be changed to other drivers for cloud deployment
